language: python

before_install:
  - sudo wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/bin/chromedriver
  - sudo chown root:root /usr/bin/chromedriver
  - sudo chmod +x /usr/bin/chromedriver
  
install: 
  - pip install selenium
  
script: python tests/test.py
